### ISSUE TITLE
Feature: allow to use ruby-vips or imagemagick for performance

### ISSUE THREAD

**Issue by pftg** [donv/capybara-screenshot-diff#15]
There is a performance issue on finding changed parts of the screenshots. We do a brute force solution. For images with 1400x1400, we will have 1400 * 1400 cycles. We could improve that by finding a difference with ready solutions and with compiled native libs. That should improve test speed. 

Cons of this that we will have more dependencies and variations, which increases complexity.

The idea is to introduce a bridge pattern with several implementations that should be selected in the configuration.

**Comment by donv** [comment]
Hi @pftg !

Performance is indeed a problem.  I would welcome any work on this field.

We already have one instance of a pattern with multiple implementations in the use of chunky_png and oily_png.  Please take that into account when researching solutions.

Please also give priority to equal images over changed images since the absolutely most common case are unchanged images.

I am looking forward to your ideas and will try to make merging smooth :)

**Comment by pftg** [comment]
Great @donv `equal images` is what I found they can do without brute-force solution. I'll give some version on weekend

**Comment by pftg** [comment]
@donv I just realize more real date will be on the next week.
